export const designStyles = {
  auto: { label: 'Match my brief', direction: 'Choose a visual language that fits the subject and requested audience. A research portfolio, product page, creative studio and developer site must look different.' },
  editorial: { label: 'Editorial', direction: 'Editorial: warm ivory, near-black ink, a restrained ochre accent, Georgia display headings and crisp sans-serif body. Use an asymmetric two-column opening, thin rules, numbered sections, and a generous magazine rhythm.' },
  studio: { label: 'Creative studio', direction: 'Creative studio: deep ink, warm white and vivid orange. Bold sans-serif display type, an off-center opening, a CSS-built geometric composition and varied full-width sections. Avoid glass, purple gradients and repeated rounded cards.' },
  technical: { label: 'Precision', direction: 'Precision: pale blue-gray, navy and cobalt. System sans-serif with small monospace labels, an ordered grid, confident typography and clear project rows. Restrained radius, subtle borders and accessible interaction states.' },
};
export function designBrief(style='auto') { return (designStyles[style]||designStyles.auto).direction + ' Establish exact background/ink/accent roles, heading/body font families, type scale, max content width, spacing scale and a distinctive hero composition in the plan layout. Carry these decisions through every section. Design around real content, never invent numbers, awards, clients or testimonials. Prefer structured lists, timelines, split layouts and purposeful visual compositions over generic card grids. Specify desktop and mobile behavior. CSS-only decoration is permitted; no image placeholders. Keep user-requested design choices above the preset.'; }
export function designCSS(plan) {
  const [ink='#172623',paper='#f6f6ee',accent='#b7eb73']=plan.palette;
  const serif=/Georgia|serif/i.test(plan.typography)&&!/sans-serif only/i.test(plan.typography);
  return `:root{--ink:${ink};--paper:${paper};--accent:${accent};--content-width:1200px;--space:clamp(24px,5vw,80px)}body{background:var(--paper);color:var(--ink)}body>section{padding:clamp(48px,7vw,100px) max(24px,calc((100vw - var(--content-width))/2));overflow-wrap:break-word}h1,h2{font-family:${serif?'Georgia,serif':'Arial,Helvetica,sans-serif'};text-wrap:balance}p{max-width:70ch}a,button{transition:background-color .18s,color .18s,transform .18s}a:focus-visible,button:focus-visible,summary:focus-visible{outline:3px solid currentColor;outline-offset:5px}.ew-container{max-width:var(--content-width);margin-inline:auto}.ew-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,1fr);gap:var(--space);align-items:center}.ew-eyebrow{font:11px/1.5 Arial,sans-serif;text-transform:uppercase;letter-spacing:.14em;color:var(--accent);margin-bottom:24px}.ew-display{font-size:clamp(56px,8vw,112px);font-weight:400;line-height:.98;letter-spacing:-.05em;max-width:11ch}.ew-intro{font-size:clamp(17px,1.5vw,21px);max-width:38ch}.ew-line{border:0;border-top:1px solid currentColor;opacity:.25;margin:32px 0}.ew-nav{display:flex;justify-content:space-between;align-items:center;gap:24px;padding:0 0 24px;border-bottom:1px solid currentColor;margin-bottom:var(--space)}.ew-nav div{display:flex;gap:24px}.ew-button{display:inline-block;padding:14px 22px;background:var(--ink);color:var(--paper);border-radius:4px;text-decoration:none}.ew-row{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px;padding:32px 0;border-top:1px solid currentColor}.ew-row h3{margin:0;font-size:clamp(24px,3vw,36px);font-weight:400}.ew-row p{margin:0}.ew-art{position:relative;min-height:320px;border-block:1px solid currentColor;overflow:hidden}.ew-art::before{content:'';position:absolute;width:72%;aspect-ratio:1;border-radius:50%;background:var(--accent);left:0;top:10%}.ew-art::after{content:'';position:absolute;inset:24% 0 10% 36%;border:1px solid currentColor}.ew-muted{opacity:.65;font-size:13px}@media(max-width:700px){.ew-grid,.ew-row{grid-template-columns:1fr}.ew-nav{align-items:flex-start;flex-direction:column}.ew-nav div{gap:16px}.ew-display{font-size:clamp(48px,13vw,72px)}.ew-art{min-height:240px}}@media(max-width:640px){body>section{padding-left:24px;padding-right:24px}h1{font-size:clamp(40px,11vw,64px)}h2{font-size:clamp(28px,8vw,42px)}}`;
}
export const designKit='Shared CSS already provides .ew-container (1200px centered), .ew-grid (responsive asymmetric columns), .ew-eyebrow, .ew-display (large responsive display), .ew-intro, .ew-line, .ew-nav (masthead + nav), .ew-button, .ew-row (responsive project row), .ew-art (CSS circle/outline composition), .ew-muted. Reuse these where they fit. Do not rewrite shared colors, fonts, base spacing or responsive rules. Add only purposeful scoped CSS, usually under 2,000 characters per section. A custom requested composition may override the primitives. Keep HTML concise; no decorative filler or repeated disclosures.';
