import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';

const root=path.resolve(import.meta.dirname,'../knowledge');
let manifest;
const cache=new Map();
// A transparent estimate, not a claim about any provider's tokenizer.
export function estimateTokens(value){const text=typeof value==='string'?value:JSON.stringify(value)||'';let ascii=0,other=0;for(const char of text)char.codePointAt(0)<128?ascii++:other++;return Math.ceil(ascii/3)+other*2;}
export function requestStage(task){return /review|inspect|check|repair.*review/i.test(task)?'check':/plan|extract|analy[sz]/i.test(task)?'plan':/selected|marked|edit|spoken change/i.test(task)?'edit':'build';}
export async function knowledgeManifest(){return manifest??=JSON.parse(await fs.readFile(path.join(root,'manifest.json'),'utf8'));}
export async function knowledgeText(id){const item=(await knowledgeManifest()).items.find(item=>item.id===id);if(!item||!item.licenseVerified||!item.enabled)throw new Error('Unknown or unreviewed knowledge item.');if(cache.has(id))return cache.get(id);const file=path.resolve(root,item.file);if(!file.startsWith(root+path.sep)||(await fs.lstat(file)).isSymbolicLink())throw new Error('Unsafe knowledge path.');const bytes=await fs.readFile(file);if(createHash('sha256').update(bytes).digest('hex')!==item.sha256)throw new Error('Knowledge integrity check failed. Restore the reviewed installation.');const text=bytes.toString('utf8');cache.set(id,text);return text;}
export const layerBudgets={core:600,rules:1500,style:1200,sections:1200,components:500,project:900};
function fitParagraphs(text,budget){if(estimateTokens(text)<=budget)return text;let result='';for(const paragraph of text.split(/\n\s*\n/)){if(estimateTokens(result+'\n\n'+paragraph)>budget)break;result+=(result?'\n\n':'')+paragraph;}return result;}
export function assembleKnowledge(blocks,stage){const remaining={...layerBudgets},loaded=[],omitted=[];for(const block of blocks){const budget=remaining[block.layer]??0;const original=estimateTokens(block.text);const text=block.atomic?original<=budget?block.text:'':fitParagraphs(block.text,budget);if(!text){omitted.push({ids:block.ids,reason:'layer budget'});continue;}const estimatedTokens=estimateTokens(text);remaining[block.layer]-=estimatedTokens;loaded.push({...block,text,estimatedTokens,shortened:estimatedTokens<original});}return {ids:[...new Set(loaded.flatMap(block=>block.ids||[]))],text:loaded.map(block=>block.text).join('\n\n'),budget:{stage,estimatedTokens:loaded.reduce((n,b)=>n+b.estimatedTokens,0),method:'ASCII characters / 3; other code points × 2. Estimates, not billed tokens.',layers:loaded.map(({ids,layer,estimatedTokens,shortened})=>({ids,layer,estimatedTokens,shortened})),omitted}};}

export async function coreKnowledge(){return knowledgeText('core');}
export async function componentKnowledge(task){const registry=JSON.parse(await fs.readFile(path.join(root,'components/registry.json'),'utf8')),id=/tab|navigation/i.test(task)?'tabs':/faq|accordion|details|expand/i.test(task)?'disclosure':/toggle|compare/i.test(task)?'toggle':undefined,item=registry.components.find(item=>item.id===id);if(!item?.licenseVerified)return null;const file=path.resolve(root,item.file);if(!file.startsWith(root+path.sep)||(await fs.lstat(file)).isSymbolicLink())throw new Error('Unsafe component reference.');const bytes=await fs.readFile(file);if(createHash('sha256').update(bytes).digest('hex')!==item.sha256)throw new Error('Component reference integrity check failed.');return {ids:['component:'+id],layer:'components',atomic:true,text:`Original MIT control example. Adapt behaviour to supplied content; keep its notice. Inline only compatible helpers, not undeclared imports. Shared instances require explicit edit scope.\n${bytes.toString('utf8')}`};}
