import './workbench.css';
import {browserChecks} from './toolkit.js';

export function workbench(parent,api,run,refresh){
 const card=document.createElement('section');card.className='card workbench';card.id='workbench';card.hidden=true;
 card.innerHTML='<div class="workbench-heading"><div><span class="eyebrow">BUILD WITH EVIDENCE</span><h3>Project checkup</h3></div><button id="run-quality" class="outline-button" type="button">Run local checks</button></div><p class="card-description">Find issues, review a focused AI repair, and keep every revision.</p><div id="quality-report" role="status"></div><div id="quality-findings"></div><section id="repair-review" class="repair-review" hidden><strong id="repair-summary"></strong><div id="repair-diffs"></div><div class="workbench-actions"><button type="button" id="apply-repair" class="primary-button">Apply reviewed repair</button><button type="button" id="discard-repair" class="text-button">Discard</button></div></section><details class="revision-history"><summary>Your project history</summary><div id="revision-list"></div><section id="revision-diff" hidden><strong id="revision-label"></strong><div id="revision-files"></div><button type="button" id="restore-revision" class="outline-button">Restore this revision</button></section></details><small class="check-scope">Source checks inspect syntax and structure without running project tests. Use the live page check below for browser evidence.</small>';
 const updateBrowserChecks=browserChecks(card,api,run,refresh);
 parent.insertBefore(card,parent.querySelector('.status-card'));const $=id=>card.querySelector('#'+id);let current,reviewIndex;
 const diffs=(parent,changes)=>{parent.replaceChildren(...changes.map(change=>{const detail=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent=`${change.path} · ${change.kind}`;pre.textContent=change.diff;detail.append(summary,pre);return detail;}));};
 $('run-quality').onclick=()=>run(async()=>{await api.qualityCheck();await refresh();});
 $('apply-repair').onclick=()=>run(async()=>{await api.applyRepair(current.repair.id);await refresh();});
 $('discard-repair').onclick=()=>run(async()=>{await api.discardRepair();await refresh();});
 $('restore-revision').onclick=()=>run(async()=>{await api.restoreRevision(reviewIndex);$('revision-diff').hidden=true;await refresh();});
 return state=>{
  if(current?.project?.directory!==state.project?.directory||current?.history?.cursor!==state.history?.cursor)$('revision-diff').hidden=true;
  updateBrowserChecks(state);
  current=state;card.hidden=!state.project;if(!state.project)return;
  $('run-quality').disabled=state.busy;$('apply-repair').disabled=state.busy;$('discard-repair').disabled=state.busy;$('restore-revision').disabled=state.busy||reviewIndex===state.history?.cursor;
  const report=state.quality;$('quality-report').textContent=!report?'No checks run for this project yet.':report.stale?'Project changed since the last check. Run it again.':`${report.errors} errors · ${report.warnings} suggestions · ${report.checks.filter(c=>c.passed).length} checks passed${report.skipped.length?` · ${report.skipped.length} skipped`:''}`;
  $('quality-report').dataset.tone=report&&!report.stale&&report.errors?'error':'ready';
  $('quality-findings').replaceChildren();
  if(report&&!report.stale){for(const finding of report.findings){const row=document.createElement('div'),badge=document.createElement('span'),body=document.createElement('div'),title=document.createElement('strong'),text=document.createElement('p'),button=document.createElement('button');row.className='quality-finding';row.dataset.finding=finding.id;badge.className='finding-badge';badge.textContent=finding.severity==='error'?'!':'·';title.textContent=finding.file;text.textContent=finding.message;body.append(title,text);button.type='button';button.className='text-button';button.textContent='Prepare AI repair';button.disabled=state.busy||(!finding.targetId&&!state.project.files);button.onclick=()=>run(async()=>{await api.proposeRepair(finding.id);await refresh();$('repair-review').scrollIntoView({behavior:'smooth',block:'nearest'});});row.append(badge,body,button);$('quality-findings').append(row);}if(report.skipped.length){const note=document.createElement('p');note.className='check-skipped';note.textContent=report.skipped.join('; ');$('quality-findings').append(note);}}
  $('repair-review').hidden=!state.repair;if(state.repair){$('repair-summary').textContent=state.repair.summary;diffs($('repair-diffs'),state.repair.changes);}
  $('revision-list').replaceChildren(...(state.history?.versions||[]).map((version,index)=>{const button=document.createElement('button');button.type='button';button.className='revision-row';button.disabled=state.busy;button.innerHTML='<span></span><small></small>';button.querySelector('span').textContent=`${index===state.history.cursor?'●':'○'} ${version.label}`;button.querySelector('small').textContent=`#${index}`;button.onclick=()=>run(async()=>{const review=await api.revisionReview(index);if(current.project?.directory!==state.project.directory)return;reviewIndex=index;$('revision-label').textContent=`Revision ${index}: ${review.label}`;diffs($('revision-files'),review.changes);if(!review.changes.length)$('revision-files').textContent='This revision changes project metadata only.';$('revision-diff').hidden=false;$('restore-revision').disabled=index===current.history.cursor||current.busy;});return button;}));
 };
}
